### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by macaulishxcoo** [statusrank/A-Generic-Framework-for-Optimizing-Two-way-Partial-AUC#1]
请问下，我在执行train.py文件时报错：
Traceback (most recent call last):
  File "D:\30_workspace\pytorch_02\A-Generic-Framework-for-Optimizing-Two-way-Partial-AUC-main\train.py", line 197, in <module>
    json_path = sys.argv[2]
IndexError: list index out of range.
报错的具体的几行代码如下：
 json_path = sys.argv[2]
    if sys.argv[1].startswith('cifar'):
        json_path += '_cifar'
        path = sys.argv[1].strip().split("-")[1]
        print(path)
        if path == '100':
            json_path += "_100"
    elif sys.argv[1] == 'tiny-imagenet-200':
        json_path += '_tiny_imagenet'
这几行代码是要将data文件夹下的cifar-10-long-tail，cifar-100-long-tail以及tiny-imagenet-200的文件名获取吗？源码中只有cifar-10-long-tail，是不是缺了两个数据集呢？但是我补充了这两个数据集然后在终端执行python train.py cifar-10-long-tail cifar-100-long-tail tiny-imagenet-200还是报这个错误。请问下，这个具体应该怎么修改呢？谢谢！！！

**Comment by macaulishxcoo** [comment]
而且，程序我是windows下运行的，这个会有影响吗？

**Comment by statusrank** [comment]
You can find the newest version of our code at https://github.com/statusrank/XCurve. Thanks for ur attention.
